### ISSUE TITLE
Tiny Tapeout 6 Submission Issues [Action required]

### ISSUE THREAD

**Issue by urish** [kevinwguan/tt06-kevinwguan#1]
Hi, congrats on submitting to Tiny Tapeout 6!

Unfortunately, there are some issues with the submission that prevent it from being integrated into the shuttle:

1. `VPWR` and `VGND` rails on metal4 are are not exported as pin under their whole length
2. Some of the INPUTS are shorted to VGND (e.g. `ena`, `rst_n`, `clk`, and the `uin_in` ports)

In addition, @smunaut did a quick review of the design, and found some potential issues:

1. Power seems to have been routed as a normal signal wire, using a thin wires, and with one via connecting the power rail. With that configuration, that module might have issues if it tries to consume more than ~ 300 uA
2. There is also a massive amount of routing on li (which has pretty high resistance)

We suggest to fix the issues and resubmit through https://app.tinytapeout.com/projects/586 before the shuttle's deadline (about 11 hours from now). Otherwise, we won't be able to include the project in Tiny Tapeout 6 (and it looks like a cool project, so we'd love to have it in).

**Comment by urish** [comment]
cc @cavelcu

**Comment by cavelcu** [comment]
Thank you very much Uri, we are revising and evaluating our options.

**Comment by kevinwguan** [comment]
Thanks I will take a look.

**Comment by kevinwguan** [comment]
Is the local interconnect problem a dealbreaker? Some of the locali is used simply for ground

**Comment by kevinwguan** [comment]
First two issues are easily fixed

**Comment by urish** [comment]
Best if you could come on [discord](https://www.tinytapeout.com/discord) to discuss it there - it might be an issue. If you did simulation on the extracted layout that also includes the parasitics and got the expected results, then it's probably okay. But otherwise, it's a bet :-)

**Comment by cavelcu** [comment]
I just submitted a new revision for this project. Please let us know if everything is under control

**Comment by urish** [comment]
Thanks! I ran a special test to see if it integrates with the chip in isolation, so instead of waiting for ~2 hours to know, we'll know in about 20 minutes. You can follow it here:

https://github.com/TinyTapeout/tinytapeout-06-staging/actions/runs/8756963308

**Comment by kevinwguan** [comment]
Looks like it passed

**Comment by urish** [comment]
Awesome!

**Comment by cavelcu** [comment]
Awesome. Thank you very much for your help Uri

**Comment by urish** [comment]
When submitting the combined chip to efabless, we encountered fom density (nwell/tap) issues. We tracked them down to where this design is placed:

![image](https://github.com/kevinwguan/tt06-kevinwguan/assets/892318/0625e6f6-e580-4018-b644-40f39c166aba)

Unfortunately, this means we'll have to remove this design from TT06 in order to make it for the efabless tape out deadline. I'm sorry.

**Comment by urish** [comment]
Good news! 

Efabless had some issues with their submission system, so I took advantage of the delay it caused and tried to reposition your project in attempt to find a spot where the fom density meet the requirements. And I finally found such spot!

This means that your design will be fabricated on Tiny Tapeout 6. Congratulations!

p.s. you can find the final combined TT chip file we submitted to the fab here: https://github.com/TinyTapeout/tinytapeout-06/releases/tag/tapeout-ci2404

**Comment by kevinwguan** [comment]
Thank you so much!
